# =============================================================================
# schema.py — Request Body Schema (Pydantic Model)
# =============================================================================
# Defines ChatMessage — the data structure the client must send to POST /chat.
#
# Key concepts used:
#   - Annotated + Field : type hints and metadata (validation, docs) in one place
#   - Literal           : restricts a field to a fixed set of allowed values
#   - Optional          : marks fields the client may omit (defaults to None)
#   - computed_field    : auto-generates bmi and obesity — never sent by the client
# =============================================================================

from pydantic import BaseModel, Field, computed_field
from typing import Optional, Annotated, Literal

from utils import calculate_bmi, calculate_obesity


class ChatMessage(BaseModel):
    """
    Validated request body for POST /chat.

    Required fields (must be provided by the client):
        name, age, gender, text

    Optional fields (client may omit — defaults to None):
        city, height, weight, exercise, sleep_hours, smooking

    Computed fields (auto-generated by Pydantic — never sent by the client):
        bmi, obesity
    """

    # ── Required fields ──────────────────────────────────────────────────────

    name: Annotated[str, Field(
        ...,
        description="Full name of the person",
        min_length=5,
        max_length=50,
        json_schema_extra={"example": "Alice Smith"}
    )]

    age: Annotated[int, Field(
        ...,
        description="Age of the person (0–120)",
        ge=0,
        le=120,
        json_schema_extra={"example": 30}
    )]

    gender: Annotated[Literal["male", "female"], Field(
        ...,
        description="Biological gender",
        json_schema_extra={"example": "female"}
    )]

    text: Annotated[str, Field(
        ...,
        description="The patient's current health concern",
        min_length=10,
        max_length=1000,
        json_schema_extra={"example": "I feel tired all the time and cannot focus at work."}
    )]

    # ── Optional fields ───────────────────────────────────────────────────────

    city: Annotated[Optional[str], Field(
        default=None,
        description="City where the person is located",
        max_length=100,
        json_schema_extra={"example": "New York"}
    )]

    height: Annotated[Optional[float], Field(
        default=None,
        description="Height in centimeters",
        ge=0,
        le=300,
        json_schema_extra={"example": 175.5}
    )]

    weight: Annotated[Optional[float], Field(
        default=None,
        description="Weight in kilograms",
        ge=0,
        le=500,
        json_schema_extra={"example": 70.2}
    )]

    exercise: Annotated[Optional[Literal["none", "light", "moderate", "heavy"]], Field(
        default=None,
        description="Weekly exercise frequency",
        json_schema_extra={"example": "moderate"}
    )]

    sleep_hours: Annotated[Optional[float], Field(
        default=None,
        description="Average hours of sleep per night",
        ge=0,
        le=24,
        json_schema_extra={"example": 7.5}
    )]

    smooking: Annotated[Optional[Literal["yes", "no"]], Field(
        default=None,
        description="Whether the person smokes",
        json_schema_extra={"example": "no"}
    )]

    # ── Computed fields (auto-generated — never sent by the client) ───────────

    @computed_field
    @property
    def bmi(self) -> Optional[float]:
        # Delegates to utils.calculate_bmi — returns None if height or weight is missing.
        return calculate_bmi(self.weight, self.height)

    @computed_field
    @property
    def obesity(self) -> Optional[str]:
        # Derived from bmi — returns None if bmi could not be computed.
        return calculate_obesity(self.bmi)
